# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\funny\OneDrive\Документы\DST_Tools\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(810, 320)
        MainWindow.setMinimumSize(QtCore.QSize(810, 320))
        MainWindow.setMaximumSize(QtCore.QSize(810, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\funny\\OneDrive\\Документы\\DST_Tools\\scripts/Icon\'s/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 280, 790, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(10, 10, 170, 30))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(550, 10, 170, 30))
        self.pushButton2.setObjectName("pushButton2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 50, 790, 220))
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(190, 10, 170, 30))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(370, 10, 170, 30))
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(730, 10, 30, 30))
        self.pushButton5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\funny\\OneDrive\\Документы\\DST_Tools\\scripts/Icon\'s/aroow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton5.setIcon(icon1)
        self.pushButton5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(770, 10, 30, 30))
        self.pushButton6.setMouseTracking(False)
        self.pushButton6.setAcceptDrops(False)
        self.pushButton6.setToolTipDuration(0)
        self.pushButton6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\funny\\OneDrive\\Документы\\DST_Tools\\scripts/Icon\'s/github.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton6.setIcon(icon2)
        self.pushButton6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton6.setObjectName("pushButton6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Инструменты переводчика DST"))
        self.pushButton1.setText(_translate("MainWindow", "Обновить из strings.pot"))
        self.pushButton2.setText(_translate("MainWindow", "Слить файл с  DST.po"))
        self.pushButton3.setText(_translate("MainWindow", "Сохранить пустые строки"))
        self.pushButton4.setText(_translate("MainWindow", "Проверить структуру файла"))
        self.pushButton5.setToolTip(_translate("MainWindow", "Скопировать DST.po из директории GitHub"))
        self.pushButton6.setToolTip(_translate("MainWindow", "Заменить DST.po в директории GitHub"))
